### ISSUE TITLE
Expose Cmake Generator Tags from nng-sys

### ISSUE THREAD

**Issue by Neightro** [neachdainn/nng-rs#1]
I would prefer to use a generator other than the default for building with CMake. I noticed that there are some feature flags in the nng-sys crate to control which generator is used. Unfortunately, these aren't exposed by nng-rs. I would like for feature flags to be added to cargo.toml to allow for the configuration of CMake when building nng-rs.

**Comment by neachdainn** [comment]
[Tracking Issue: Gitlab 39][1]

The only reason those features aren't available in this library is because I personally haven't needed them and (until now) noone has ever asked for them. I'm a bit swamped right now but I will try to get them added by the end of the week. Alternatively, I am also open to pull requests.

If you need them to be available immediately, you can probably set them via the [patch section][2].

[1]: https://gitlab.com/neachdainn/nng-rs/issues/39
[2]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section

**Comment by Neightro** [comment]
I totally understand—life comes first! 😃 I would be happy to look into adding that and opening a pull request.
Thanks for the link; I wasn't aware that patches existed. I'm still a bit of a beginner at Rust, so things like that are a big help for finding my way.

**Comment by neachdainn** [comment]
What generator are you trying to use? I don't necessarily want to add all of the options that we added to nng-sys because I don't have a way to test them all.

**EDIT:** And why? Cargo features aren't meant to be mutually exclusive and the different build systems are. I'm not a huge fan of how it is exposed in nng-sys but that was a compromise between me and the other author so I am leaning towards recommending the patch system and/or manually building if the default doesn't work. Letting me know more about why you want to build with a different system would be very helpful.

**Comment by Neightro** [comment]
I discovered that I could add nng-sys as a direct dependency to my own project and require whatever generator I need. nng-sys seems to be building fine for me using Ninja, so I don't have any more issues personally. You are welcome to close the issue; I'll leave that up to you. However, I can't help but think that including some information in the readme could help prevent someone from having the same problem in the future.

To answer your question about why I wanted to use a different build system, it was because I was having problems using the default Windows build system, Visual Studio 2017 x64. I have a simple installation of Visual Studio 2019, though the build system doesn't seem to accept that version, and older versions seem to be hard to come by (to my knowledge, there is no official download from Microsoft).

I agree that the way that the generators were exposed in nng-sys was not a great solution, and they should probably switch the default version for Windows to something else like Visual Studio 2019, or ideally something that won't go out of date next year, such as Ninja.

Thank you for your support! I wasn't expecting such a quick response, and I appreciate your willingness to offer suggestions.

**Comment by neachdainn** [comment]
> However, I can't help but think that including some information in the readme could help prevent someone from having the same problem in the future.

That's a good point. I'll leave this issue open as a reminder to add that soon.

> ...they should probably switch the default version for Windows to something else like Visual Studio 2019, or ideally something that won't go out of date next year, such as Ninja.

I think this is already in progress [here][1]. I don't have a Windows machine to test this stuff on and I definitely don't develop on Windows, so I've sort of just left that to other people. It also wouldn't hurt to open an issue in that repository to start a discussion with people who use Windows.

[1]: https://github.com/jeikabu/nng-rust/pull/22

**Comment by Neightro** [comment]
It couldn't hurt to chime in on the issue. It would be worth mentioning to the development team that I got blocked because of the issue, which is significant.

If you ever wanted to test Windows stuff, I'm sure there is a simple VM that could help, though I'm no expert on that subject.

**Comment by neachdainn** [comment]
Closed via [Gitlab merge request 43][1].

[1]: https://gitlab.com/neachdainn/nng-rs/merge_requests/43

**Comment by Neightro** [comment]
The amended Readme looks good! 

Just thought I'd note that it shouldn't be necessary to disable `build-nng`, since nng-sys is configured so that if any of the cmake generators are enabled, then `build-nng` will be enabled as well.

**Comment by neachdainn** [comment]
Yeah, but it's a compatibility thing. If I ever change how the nng-sys feature works I don't have to worry about updating the documentation for nng-rs. Plus, I think it's just cleaner to not "ask" Cargo to build NNG when you don't want to build NNG.

**EDIT:**  In the third case, manually building, you will have to disable the feature. Having that feature enabled will both build NNG and [override the link path][1] so that Cargo finds the newly built one before the one you actually want to link.

[1]: https://github.com/jeikabu/nng-rust/blob/master/build.rs#L57
